name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run tests
        run: |
          pytest

  lint:
    runs-on: ubuntu-latest
    name: Linting
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: MyPy Type Check
        uses: tsuyoshicho/action-mypy@v4
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Execute mypy check
          execute_command: "mypy pokepocketsim/ tests/ --show-column-numbers"

      - name: Run Flake8 with annotations
        continue-on-error: true
        run: |
          flake8 pokepocketsim/ tests/ --format='::error file=%(path)s,line=%(row)d,col=%(col)d::[%(code)s] %(text)s' || true

      - name: Run Black check with annotations
        continue-on-error: true
        run: |
          black --check --diff pokepocketsim/ tests/ || {
            echo "::error::Code formatting issues found. Run 'black pokepocketsim/ tests/' to fix."
          }

      - name: Run isort check with annotations
        continue-on-error: true
        run: |
          isort --check-only --diff pokepocketsim/ tests/ || {
            echo "::error::Import sorting issues found. Run 'isort pokepocketsim/ tests/' to fix."
          }

      - name: Generate linting summary
        run: |
          echo "## Linting Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### MyPy" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          mypy pokepocketsim/ tests/ --show-column-numbers || echo "MyPy found type issues"
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### Flake8" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          flake8 pokepocketsim/ tests/ || echo "Flake8 found style issues"
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### Black (Code Formatting)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          black --check --diff pokepocketsim/ tests/ || echo "Code formatting issues found"
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### isort (Import Sorting)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          isort --check-only --diff pokepocketsim/ tests/ || echo "Import sorting issues found"
          echo '```' >> $GITHUB_STEP_SUMMARY
